[package]
name = "network-generator"
version = "0.1.0"
authors = ["Skillr <skillr@tuta.io>"]
edition = "2018"

[dependencies]
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libmath = "0.2.1"